baseURL = 'http://nice2me2.github.io/'
languageCode = 'en-us'
title = '天神欧力给'
theme = 'maupassant' 

# 目录
toc = true

# 高亮样式
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

# 添加菜单
[menu]
  [[menu.main]]
    identifier = "poems"
    name = "诗文赏析"
    url = "/poems/"
    weight = 2

# 图片点击放大
[params]
  fancybox = true